#I need to import a task nodejs.yaml in catalogue

- name: print the app-version
  debug:
   msg: "App version is : {{App_version}}"

- name: Install NodeJs
  ansible.builtin.import_role:
      name: common
      tasks_from: nodejs

- name: Set-up app(user & directory)
  ansible.builtin.import_role:
      name: common
      tasks_from: app-setup


- name: Install the dependencies.
  ansible.builtin.command: npm install 
  args:
    chdir: /app

- name: Set-up service
  ansible.builtin.import_role:
      name: common
      tasks_from: systemd-setup-service

# we are doing this  as part of MongoDB itself

# - name: setup MongoDB
#   ansible.builtin.import_role:
#       name: common
#       tasks_from: load-mongo-schema


