- name: check user exits or not
  ansible.builtin.command: id roboshop
  register: out  #out is variable name
  ignore_errors: true

- when: out.rc != 0
  name: create user roboshop
  become: true #we need sudo access for this task only
  ansible.builtin.user:
    name: roboshop

  # check the exist or not
- name: check /app directory exist or not
  ansible.builtin.stat:
    path: /app
  register: directory # we run the above command and output will stored inside this "directory" variable

- name: print the directory stat
  ansible.builtin.debug:
    msg: "output {{directory}}"

- when: directory.stat.exists == False 
  name: Create /app directory 
  ansible.builtin.file:
    path: /app
    state: directory

# - name: Download the {{component}} Artifact
#   ansible.builtin.get_url:
#     url:  https://roboshop-builds.s3.amazonaws.com/{{component}}.zip
#     dest: /tmp

- name: Download Artifact from Nexus
  ansible.builtin.get_url:
    url: "{{nexus_url}}/{{component}}/{{group_id}}/{{component}}/{{app_version}}/{{component}}-{{app_version}}.zip"
    dest: "/app/{{component}}-{{app_version}}.zip"
    username: "{{nexus_username}}"
    password: "{{nexus_password}}"
    
- name: extract {{component}} Artifact
  ansible.builtin.unarchive:
    src: "/app/{{component}}-{{app_version}}.zip"      
    dest: "/app"
    remote_src: yes