- name: Install Python 3.6
  ansible.builtin.dnf:
    name: "{{item}}"
    state: installed
  loop:
  - python36
  - gcc 
  - python3-devel

  - hosts: all
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
